# Generated by Django 4.0.5 on 2022-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_swipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='img',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
